### ISSUE TITLE
restore login ability

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore#321]
# Story
we are unable to login locally or in production (vercel). the [workaround](https://github.com/scientist-softserv/webstore/issues/321#issuecomment-1800164936) mentioned in the comments below does not work for this error.

this is not affecting phenovista's digital storefront.

# Acceptance Criteria
- [ ] we are able to log in to the correct marketplace in local dev
- [ ] we are able to log in to the correct marketplace in production

# Screenshots / Video
<details>
<summary>browser error</summary>

<img width="695" alt="image" src="https://github.com/scientist-softserv/webstore/assets/29032869/b418dbca-afdc-44e8-a563-98d31c00509b">
</details>

<hr>
<details>
<summary>INITIAL ISSUE</summary>

# Story
locally, we are receiving a CORS error when pressing the "sign in" button. the same error is not seen at https://webstore-staging.vercel.app/.

# Acceptance Criteria
- [ ] we are able to log in to the correct marketplace in local dev again

# Screenshots / Video
![image](https://github.com/scientist-softserv/webstore/assets/29032869/3c6bc456-f3d1-489b-bd62-5102f9351db9)

# Testing Instructions and Sample Files
- from the home page, click the "sign in" button and be redirected to the marketplace on the scientist.com domain
</details>

**Comment by alishaevn** [comment]
for the time being, we can get around this error locally by updating the code as stated below. it means we get taken to a "middle man" site where we have to choose to be taken to scientist. however, since this is only a problem locally, I'm setting this aside for more pressing issues.

``` js
# _app.js

# change this
signIn: () => signIn(process.env.NEXT_PUBLIC_PROVIDER_NAME)

# to this
signIn: () => signIn()
```

**Comment by alishaevn** [comment]
unsure if it's related to the initial problem, but we are now unable to sign in locally, or on the production (vercel) site.
adelle [reported it](https://assaydepot.slack.com/archives/C03FZDALABG/p1708715918923929) on feb 23. I was able to duplicate the error in prod that day. today, I saw it in local dev too.

once I clicked "sign in", I was redirected to the supplier's marketplace on scientist.com. I was able to log in, but the redirect erred. it took me to the nextauth default login page with a "Try signing in with a different account." message. clicking "Sign in with beachsidebiotech" didn't work. the reload button next to the url bar spun like it was trying to go somewhere, but once it finished we never left the page. going back to the homepage still showed that I wasn't signed in.

the server logs show the error below:
``` bash
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error Request failed with status code 404 {
  message: 'Request failed with status code 404',
  stack: 'AxiosError: Request failed with status code 404\n' +
    '    at settle (file:///Users/alishaevn/Work/webstore/node_modules/axios/lib/core/settle.js:19:12)\n' +
    '    at Unzip.handleStreamEnd (file:///Users/alishaevn/Work/webstore/node_modules/axios/lib/adapters/http.js:512:11)\n' +
    '    at Unzip.emit (node:events:525:35)\n' +
    '    at Unzip.emit (node:domain:489:12)\n' +
    '    at endReadableNT (node:internal/streams/readable:1359:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)',
  name: 'AxiosError'
}
```

<details>
<summary>browser error</summary>

<img width="695" alt="image" src="https://github.com/scientist-softserv/webstore/assets/29032869/b418dbca-afdc-44e8-a563-98d31c00509b">
</details>
